### ISSUE TITLE
Update my ugly photo

### ISSUE THREAD

**Issue by VictorChen** [VictorChen/VictorChen#27]
:smile:

**Comment by tolbahadi** [comment]
:+1:

**Comment by arwinsardana** [comment]
:+1:

**Comment by arwinsardana** [comment]
Would it be possible to remove the photo entirely?

**Comment by tolbahadi** [comment]
Yeah I think that will be better. I will almost be impossible to find a suitable photo.

**Comment by arwinsardana** [comment]
Thanks @tolbahadi for you thoughts. Sounds like we're all in agreement. @VictorChen can you make this change please?

**Comment by arwinsardana** [comment]
@VictorChen just wondering - any update on this?

**Comment by tolbahadi** [comment]
How about this:

![image](https://cloud.githubusercontent.com/assets/653088/12621617/557945e6-c4ef-11e5-8816-8c0c647a238c.png)

I can prepare a pull request if you guys like it.

**Comment by arwinsardana** [comment]
:+1: @tolbahadi thanks for actually taking care of this. The library owner is clearly unresponsive...

**Comment by VictorChen** [comment]
LOOOOOOOOOOOOL

**Comment by VictorChen** [comment]
I'm gathering client feedback before doing work on this

**Comment by VictorChen** [comment]
This will be on the roadmap for next quarter

**Comment by VictorChen** [comment]
7d3be53033495ac8ef27503471e24eb0648797e8
